### PR TITLE
Ring modulator

### PR DESCRIPTION
**Pull request by JohnPaulHarold**
This PR adds a ring modulator effect.

* adds tests
* adds effect
* adds example to readme
* adds demo to site

De-caffeinated from here, http://webaudio.prototyping.bbc.co.uk/ring-modulator/

@alemangui please review

n.b: I guess the shape of the waveform could be added as a configurable option.
n.b 2: this, or the other PR, will almost certainly need to have master merged back in before commit. I can do that when/if the other PR is accepted.
n.b 3: this effect would be ideal for a mic demo with getUserMedia, if only for people to try and replicate that Dalek voice effect. I can look at that later if it's felt that's worthwhile.

### CODE REVIEW

**Comment by alemangui** [comment]
Hey man, thanks for this PR! I also think this effect would be good for a mic demo, which can be easily accomplished with a Pz.Sound coming from the input. 

I have a few more features and bug fixes to finish up before I push a new version, I'll keep you posted.

**Comment by JohnPaulHarold** [comment]
@alemangui glad you liked it.

I agree about the mic demo, but I didn't set that as the default as, if you don't have a mic, then it would fall back to not hearing the effect. At the time, I felt that could be remedied in a later PR, if the first PR got accepted. I'll have a look into that later, unless you want to tackle it sooner.

**Comment by alemangui** [comment]
No problem, I'm looking for a voice recording and I will add it to the site later today.

I'm playing around with the effect, it's lots of fun. I might make a few modifs to the outGain node to make it a bit more in-line with the general volume/gain, and perhaps a few minor adjustments later on, but in general it looks really good.

**Comment by alemangui** [comment]
I've also pushed the site changes to the gh-pages branch: https://alemangui.github.io/pizzicato/#ring-modulator 👍

**Comment by JohnPaulHarold** [comment]
yeah, I chose the drum loop as that seemed to really show it off the best, but yeah, some vocals would be good, and in keeping with having a different sample per effect on the demo page. With the drum sample it's fun to try and adjust the speed to the rhythm, which makes me wonder if it's possible to somehow wire that together... but for another time perhaps.

btw, I'm currently working on a tremolo effect. It does basic tremolo, but I'd like to see if I can wire in stereo panning to it also. Unless you're working on one already, in which case I'll stop.

**Pull request merged**
