### PR TITLE
Update Sound.js

### PR DESCRIPTION
**Pull request by hcollin**
Fixed the removeEffect bug, that caused a crash if the effect removed was not the first in stack.

### CODE REVIEW

**Comment by alemangui** [comment]
Wow good catch. Thanks for this.

It would be good to add a test case in ```tests > Sound.test.js```, perhaps under the ```describe('effects', ...``` suite. 

Would you be interested in adding it? Else I could add it after merging your commit.

**Comment by alemangui** [comment]
Related to #51

**Comment by hcollin** [comment]
Hi,

I could probably add it, but I cannot do it now. I still have to build a
lot stuff upon this before my speech on Web Audio Api and I only have today
to do it all. =) So if you have time, just add the test, otherwise it will
have to wait for a while  so I can properly concetrate on it.

Do you mind if I promote your library in the speech? It is only for small
group of JS enthusiast in my area (Tampere, Finland).

Best Regards,

Henrik Collin

**Comment by alemangui** [comment]
OK, I will merge your fix and make a bug-fix release.

Sure no problem! Feel free to talk about the library, and good luck in your presentation :)

**Pull request merged**
