### PR TITLE
Dub delay

### PR DESCRIPTION
**Pull request by JohnPaulHarold**
This PR adds a simple Dub delay effect.

* adds tests
* adds effect
* adds example to readme
* adds demo to site
* reorders graph on PingPong delay while I was working out a bug (which was me being silly)

Taken from here, http://blog.chrislowis.co.uk/2014/07/23/dub-delay-web-audio-api.html

@alemangui please review

### CODE REVIEW

**Comment by alemangui** [comment]
Hey, super cool effect as usual. I've been playing around with it and it's lots of fun.

I made a commit on top (57bc51c046ddf623c3f40fb318d139e29209aee1) to make a two main changes:

- I've slightly modified the way the nodes are connected to each other to avoid the first two repetitions of the delay being identical. To see this, try setting the cutoff frequency of the biquad filter to zero and play the chop.mp3 file. You'll notice that you'll get two identical repetitions, and then nothing else, instead of simply getting one. In other words, the biquad filter should be listenable from the second repetition. The commit mentioned above has a minor re-arrange of the nodes to avoid this.

- While playing around I thought that 700 would make a nice default cutoff frequency - it's easier to hear the filter effect right away. I changed it in my commit but I'm open to remarks as always.

Other than that the rest were minor style changes.

I haven't merged this branch to master - I want to see if you agree with these changes, and if so I will proceed to the merge.

Thanks a lot :)

**Comment by alemangui** [comment]
Awesome, thanks a lot :)

**Comment by chrislo** [comment]
Love it 👍

**Comment by alemangui** [comment]
@chrislo Thanks for the inspiration 👍

**Comment by JohnPaulHarold** [comment]
@chrislo double thanks in fact: I was introduced to Pizzicato via your WebAudio Weekly newsletter.

**Comment by sksar** [comment]
Love it... good work....

**Pull request merged**
