### PR TITLE
added function currentTime() to sound object

### PR DESCRIPTION
**Pull request by edgehero**
i made a issue before about it.
to check if its playing it already could be checked with source.playing

getting the currentTime was not possible, so i made a function for it ( better performance then a eventlistener + variable ) 
.currentTime() now get the current time, even when paused.

### CODE REVIEW

**Comment by alemangui** [comment]
Thanks a lot, I'm out of town but i will take a look as soon as i get back. Cheers

**Comment by edgehero** [comment]
made a bug fix, when it not been playing yet, it was not paused. so the variable playing was better here

**Comment by alemangui** [comment]
Hey man,

Thanks for the PR. Sorry for the delay, I just got back from a trip.

I have a couple questions... 

1. Just so I understand better, what is your use case for the currentTime of a sound? I'm asking this because there might be another way of achieving it, and also to ensure I'm not missing something else.
2. I noticed that you added a Volume effect in commit a21d7e6. Is this intended? What would be the difference between this and simply modifying the ```volume``` property of a sound?
3. Supposing we agree on adding the currentTime of the sounds, is there a particular reason why you decided to model it as a function ```currentTime()``` instead of a property? (e.g., ```currentTime```?)

**Comment by edgehero** [comment]
Hi @alemangui, 

the Pizzicato.context.currentTime now is just a timer, that start timing when the sound has been created. to calculate the time i just did,  Pizzicato.context.currentTime - lastTimePlayed. that would give back the correct time. but yes there is a huge problem with that. and that is that it disregards PlaybackRate and loops. do you know a way to calculate it based on playbackrate? ( it can just reset when onEnd, is fired)

2. sorry that was a mistake, i added that for my project because i needed a second channel volume ( for a crossfader) that was not influencing  the volume of the soundelement itself ( they had there own settings.) but it can also be really usefull for other people, so i could add it in another pullreqeust

**Comment by alemangui** [comment]
OK, so if I understand correctly you would like to know where in time is a file being played?

For instance, let's say you create a Sound object from a file ```song.m4a``` in loop mode . The file is 5 seconds long.

- If you have never played the file, what would you expect this timer value to be? (I suppose zero?)
- Let's say you start playing it and pause it at 00:03. Would you expect the timer to be at three seconds?
- Let's say you keep playing it for ten seconds after that and then pause it. Since it's being looped, it will end up at 00:03 again. Would you expect this value to be three seconds as well? 

Now regarding other sources...
- What would this value be for sounds coming from an oscillator, user input or function-based sounds?

**Comment by edgehero** [comment]
yes i want to have i function like your describing there.
but also regarding playbackrate, and that is where i cant really find a solution.
so with a 5 second file:
- when its playing on playbackrate 1, on 00:02 its changed to playbackrate 2.
after 1 second of that, the time should be 00:04. because the time will go 2 times as fast in that second.

problems:
1. the playbackrate should be added as an effect, because otherwise it would bug with the volume when the volume is changed. (changes the sourceNode)
2. should work even when changing the playbackrate, even with a  negative playbackrate. 

this should only be for file sounds and not for web audio api generated sounds

https://github.com/cwilso/wubwubwub this project got something like that in there already, but the code is pretty hacky/messy and hard to understand because of it.

**Comment by edgehero** [comment]
possibly found a solution, creating a new pullrequest

**Comment by edgehero** [comment]
remade the time part. its alot more powerful now.
It calculates based on playbackrate. so when turning the playbackrate to 0.5, the time will go slower.

Its made with a loop that realtime calculates how much time it should add to the time variable, based on playbackrate. i found it to be 100% accurate even when having another loop on playbackrate that changed it random, but ofcourse it also still works with normal speed and play and pause.

What do you think of this solution? 

things that need to be added before a merge: 

- does not work with loop yet, but it got the potential to support that to. currently it keeps counting on a loop.

- Fix checks

Btw. do you know a better way for setting playbackrate? currently i use sound.sourcenode.playbackrate for it. but the sourcenode changes to audiosourcenode when changing the volume of the sound element

**Comment by escaper01** [comment]
could you please show us how can we check if a specific sound is currently playing

**Comment by alemangui** [comment]
I'll close this PR since it's been a while since it was updated (the checks didn't pass).

@escaper01 feel free to ask the question by opening an Issue, I'll answer there.

**Comment by edgehero** [comment]
at the time i made a timestamp based on playbackrate
				var now = Pizzicato.context.currentTime;
				this.lastBufferTime += (now - this.lastTimeStamp) * this.lastPBR;
(this.lastPBR was the playbackrate number)

**Pull request closed without merging**
